---
title: "<h1 style='text-align:center;'> Sample size calculation </h1>"
author: "Hugo Marthinet"
date: "`r Sys.Date()`"
output:
  knitr:::html_vignette:
  toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Sample size calculation}
  %\usepackage[utf8]{inputenc}
---

\setmainfont{Calibri Light}

```{r, echo = FALSE, message = FALSE}

# If you want to create a PDF document paste the following after line 9 above:
#   pdf_document:
#     toc: true
#     highlight: tango
#     number_sections: no
#     latex_engine: xelatex    
# header-includes: 
#    - \usepackage{fontspec}

knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4L, tibble.print_max = 4L)
library(sampleSize)
```

This packages provides sample size calculation functions for various designs not provided in **pwr* and **webPower** packages.

## Cohort study


```{r, message = FALSE}
SScohort(incidence.exp = 2/1000, fact.risque = 3,
#             prop.traitement = 0.3, temps.etude = 5)
```

